

GET http://localhost:3000/posts/
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoidGFya0BnbWFpbC5jb20iLCJpYXQiOjE3MjgxMjU4MzksImV4cCI6MTcyODEyOTQzOSwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.Wio-D0pfq41FgWh4_bUI8dT-gkTez_U2POjEksyUpVI


GET http://localhost:3000/posts/3
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoidGFya0BnbWFpbC5jb20iLCJpYXQiOjE3MjgxMjU4MzksImV4cCI6MTcyODEyOTQzOSwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.Wio-D0pfq41FgWh4_bUI8dT-gkTez_U2POjEksyUpVI