PATCH http://localhost:3000/posts/
Content-Type:application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoidGFya0BnbWFpbC5jb20iLCJpYXQiOjE3MjgwMjgwODMsImV4cCI6MTcyODAzMTY4MywiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.imTdyDYKz14RDKlpW6ryj23idnXrJHpA1Kq2YSOh7fI
{
    "title":"updated post title",
    "id":3
}