POST http://localhost:3000/posts/
Content-Type:application/json
{
    "title":"this is test post title6",
    "content":"this is content of the post6",
    "coverImageUrl":"http://someurl.org/image.png",
    "slug":"this-is-content-of-the-post-6",
    "status":"published",
    "authorId":1,
    "tags":[1,2],
    "metaDataOption":{
   "metaValue":"{\"backLinks6\":\"https://backlink.org/link-6\"}"


    }
}