DELETE http://localhost:3000/posts/3
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoidGFya0BnbWFpbC5jb20iLCJpYXQiOjE3MjgwMjMzMzAsImV4cCI6MTcyODAyNjkzMCwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.XCBP5jwX3X9vujeTsuQvTJOlhMVLy22BJCTxnG82Z7k