POST http://localhost:3000/posts/
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoibWFya0BnbWFpbC5jb20iLCJpYXQiOjE3MjgwMTk0OTksImV4cCI6MTcyODAyMzA5OSwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.7cfUAKv7hH7b0Ntetzzu3xKnAf8av1QxFQImhxoieBA
{
    "title":"this is test post title3",
    "content":"this is content of the post-3",
    "coverImageUrl":"http://someurl.org/image.png",
    "slug":"this-is-content-of-the-post-3",
    "status":"published",
     "tags":[1],
    "metaDataOption":{
       "metaValue":"{\"backLinks6\":\"https://backlink.org/link-6\"}"

    }
}