POST http://localhost:3000/auth/sign-up
Content-Type:application/json
{
    "firstName":"jason",
    "lastName":"test",
    "email":"jason6@gmail.com",
    "password":"Test123@",
     "confirmPassword":"Test123@",
    "dataOfBirth":"1999-09-09",
    "bio":"Passionate software developer with experience in web development.",
    "profileImage":"https://example.com/profile-image.jpg"

}