POST http://localhost:3000/tags/
Content-Type:application/json

{
"name":"javaScript",
"slug":"javascript",
"description":"javascript related things",
"featuredImageUrl":"http://example.com/sample-image-tag.jpg"
}